In [1]:
pip install xlrd

                                              0.0/96.5 kB ? eta -:--:--
     ------------                             30.7/96.5 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 96.5/96.5 kB 1.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
df = pd.read_excel(r"C:\Users\gnani\Downloads\Lab Session1 Data.xlsx",sheet_name='Purchase data')
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   
5      C_6           22             1                 5           167   
6      C_7           15             4                 2           271   
7      C_8           18             4                 2           274   
8      C_9           21             1                 4           148   
9     C_10           16             2                 4           198   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   
5         NaN         NaN         NaN         NaN         NaN  ...   
6         NaN         NaN         NaN         NaN         NaN  ...   
7         NaN         NaN         NaN         NaN         NaN  ...   
8         NaN         NaN         NaN         NaN         NaN  ...   
9         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   
5          NaN          NaN          NaN          NaN          NaN   
6          NaN          NaN          NaN          NaN          NaN   
7          NaN          NaN          NaN          NaN          NaN   
8          NaN          NaN          NaN          NaN          NaN   
9          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 17  Unnamed: 18  Candy  Mango  Milk  
0          NaN          NaN    1.0   55.0  18.0  
1          NaN          NaN    NaN    NaN   NaN  
2          NaN          NaN    NaN    NaN   NaN  
3          NaN          NaN    NaN    NaN   NaN  
4          NaN          NaN    NaN    NaN   NaN  
5          NaN          NaN    NaN    NaN   NaN  
6          NaN          NaN    NaN    NaN   NaN  
7          NaN          NaN    NaN    NaN   NaN  
8          NaN          NaN    NaN    NaN   NaN  
9          NaN          NaN    NaN    NaN   NaN  

[10 rows x 22 columns]

In [6]:
df = df.dropna(axis=1)
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [7]:
A = df.iloc[:,1:4].to_numpy()
C = df.iloc[:,4].to_numpy()
A

array([[20,  6,  2],
       [16,  3,  6],
       [27,  6,  2],
       [19,  1,  2],
       [24,  4,  2],
       [22,  1,  5],
       [15,  4,  2],
       [18,  4,  2],
       [21,  1,  4],
       [16,  2,  4]], dtype=int64)

In [8]:
C


array([386, 289, 393, 110, 280, 167, 271, 274, 148, 198], dtype=int64)

In [9]:
dim1 = df.shape
print("The Dimension  by using shape ", dim1)
dim2 = df.ndim
print("The Dimension by using ndim ", dim2)

The Dimension using shape is (10, 5)
The Dimension using ndim is 2


In [10]:
print("No of vectors exist in vector space is ",len(df))

Number of vectors exist in vector space is  10


In [11]:
rank = np.linalg.matrix_rank(A)
print("Rank of matrix A is",rank)

NameError: name 'np' is not defined

In [58]:
A_inv = np.linalg.pinv(A)
product_costs = np.matmul(A_inv, C)
print("Cost of each product:")
print(product_costs)

Cost of each product:
[ 1. 55. 18.]
